### ISSUE TITLE
When using multiple attribute in the select tag, selecting an option causes the scroll bar to jump

### ISSUE THREAD

**Issue by andrew-ang** [Supertext/knockout.groupedOptions#5]
In the first two jsfiddle examples, when I add the `multiple` attribute to the select, the scrollbar jumps upon clicking options. More specifically, if there are two groups, then clicking either of the last two options will cause the scroll bar to jump. If there are three groups, then the last three options will cause the jump, and so on.

An interesting thing to note is that this only happens in Chrome (41.0.2272.101 (64-bit)), but not Firefox (31.5.0).

**Comment by awj100** [comment]
In its current state, the `groupedOptions` binding does not support the _multiple_ attribute.

In all honesty, I forgot about the _multiple_ attribute as it wasn't a required feature when I initially built this plugin.

The reason that this jump occurs is that it only stores a single selected item. So if you store more than one then it only recognises the first item that it comes across and - I guess - the browser's behaviour is to scroll to that selected item.

I will find the time to add support for _multiple_ but I can't promise that this'll happen in the next few days.

[Incidentally, Firefox is now up to v38, and the jump occurs there too.]

**Comment by andrew-ang** [comment]
Would there be a simple workaround to prevent this issue from happening, or perhaps even prevent any scrolling?

**Comment by awj100** [comment]
I'm afraid there's no _simple_ workaround. The way in which the plugin runs, determines what has been selected and how it stores that item against the observable would need modified.

But hey, this is open, distributed source control, so feel free to take a look at the source and have a go if you're up for the challenge.

**Comment by andrew-ang** [comment]
Until a proper fix is made, a quick and hacky way around this is to create more `<options >` equal to the number of `<optgroups>` there are, and set their `style="display:none;"`.

**Comment by awj100** [comment]
Please get the latest version and let me know if 'multiple' is now fully supported.

Note that the property on the view-model which is assigned the selected value must be an `array` or `observableArray` if `multiple` _is_ declared. If not, then an exception will be thrown upon first selection.

And likewise, if the view-model's _selected_ property is an `array` or `observableArray` and 'multiple' has _not_ been declared then an exception will similarly be thrown.
